server:
  port: 18087
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8080
  zipkin:
    base-url: localhost:9411
    discovery-client-enabled: false
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1
  thymeleaf:
    cache: false
  redis:
    host: 192.168.234.128
    port: 6379
feign:
  sentinel:
    enabled: true
