server:
  port: 18086
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8080
  zipkin:
    base-url: localhost:9411
    discovery-client-enabled: false
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1
  elasticsearch:
    rest:
      uris: http://192.168.234.128:9200
  thymeleaf:
    cache: false
feign:
  sentinel:
    enabled: true
